apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.environment }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
