apiVersion: apps/v1
kind: Deployment
metadata:
 name: k8node-deployment
 labels:
   app: k8node
spec:
 replicas: 5
 selector:
   matchLabels:
     app: k8node
 template:
   metadata:
     labels:
       app: k8node
   spec:
     containers:
       - name: k8node
         image: k8node:v1
         imagePullPolicy: Never
         ports:
           - containerPort: 3000
         env:
           - name: NODE_ENV
             value: "Default Env"
           - name: LOG_LEVEL
             value: "Default Log Level"
